---

"COURSE": "CAU_AIML_2023"
"ASSIGNMENT": "ASSIGNMENT_00"

"ID": "20190807"
"FILES":
    - "C:/Users/min/Desktop/Artech/3_2/AIML/cau-aiml-2023//assignment/assignment_00/main.py"    
"PROBLEMS": 
    - "PROBLEM_01"
    