---

"COURSE": "CAU_AIML_2023"
"ASSIGNMENT": "ASSIGNMENT_02"

"ID": "20190807"
"FILES":
    - "C:/Users/min/Desktop/Artech/3_2/AIML/assignment/assignment_02/model01_result_valid.csv" 
    - "C:/Users/min/Desktop/Artech/3_2/AIML/assignment/assignment_02/classification.py" 
"PROBLEMS": 
    - "PROBLEM_01"
