---

"COURSE": "CAU_AIML_2023"
"ASSIGNMENT": "ASSIGNMENT_01"

"ID": "20190807"
"FILES":
    - "C:/Users/min/Desktop/Artech/3_2/AIML/assignment/assignment_01/regression.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
